[tool.poetry]
name = "neonize"
version = "0.1.0"
description = "whatsmeow binder for python"
authors = ["krypton-byte <rosid6434@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
protobuf = "^4.25.1"
python-magic = "^0.4.27"
pillow = "^10.1.0"
requests = "^2.31.0"


[tool.poetry.group.dev.dependencies]
segno = "^1.6.0"
mypy-protobuf = "^3.5.0"


[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
sphinx-rtd-theme = "^2.0.0"
myst-parser = "^2.0.0"
sphinx-autodoc-typehints = "^1.25.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
docsbuild = "docs.generate:build"
build = "neonize.gocode.build:build"
