name: Docs Release

on: workflow_dispatch

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.8"
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: build docs
      run: |
        poetry sync --group docs
        uv run task docsbuild
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: docs/_build/html
