name: Auto Update whatsmeow

on:
  workflow_dispatch:
  push:
    branches:
      - musl
env:
 UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
 VERSION_MAJOR: ${{ github.event.inputs.version_major }}
 VERSION_MINOR: ${{ github.event.inputs.version_minor }}
 VERSION_PATCH: ${{ github.event.inputs.version_patch }}
 VERSION_POST: ${{ github.event.inputs.version_post }}
jobs:
  musl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1

      - name: Run script inside Alpine chroot as root
        run: |
          cat /etc/alpine-release
          apk add linux-headers
          apk add python3-dev
          apk add go
          apk add python3
          apk add uv
          apk add musl
          apk add musl-dev
          apk add musl-utils
          apk add git
          apk add gcc
        shell: alpine.sh --root {0}

      - name: Run script inside Alpine chroot as the default user (unprivileged)
        run: |
          export CGO_ENABLED=1
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          ls -la  # as you would expect, you're in your workspace directory
          uv sync
          uv sync --dev
          uv run task version --set-url "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" info
          uv run task build all
          uv build
          uv run task repack
          export UV_PUBLISH_TOKEN=${UV_PUBLISH_TOKEN}
          uv publish
        shell: alpine.sh {0}
      - name: Run script on the host system (Ubuntu)
        run: |
          cat /etc/os-release
        shell: bash
      - name: test
        run: |
          ls -la
          ls goneonize
          ls neonize